 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/folders", type: :request do
  before(:each) do
    Folder.create(name: 'Contrato_X')
  end

  let(:valid_attributes) do
    { name: 'Contrato_Y' }
  end

  let(:invalid_attributes) do
    { name: 'Contrato_X' }
  end

  describe "GET /index" do
    it "renders a successful response" do
      Folder.create! valid_attributes
      get folders_url
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_folder_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      folder = Folder.create! valid_attributes
      get edit_folder_url(folder)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Folder" do
        expect {
          post folders_url, params: { folder: valid_attributes }
        }.to change(Folder, :count).by(1)
      end

      it "redirects to the created folder" do
        post folders_url, params: { folder: valid_attributes }
        expect(response).to redirect_to(folders_url)
      end
    end

    context "with invalid parameters" do
      it "does not create a new Folder" do
        expect {
          post folders_url, params: { folder: invalid_attributes }
        }.to change(Folder, :count).by(0)
      end
    end

    context "when invalid parameters and json request" do
      it "has 422 status code" do
        post folders_url, params: { folder: invalid_attributes }, as: :json
        json_response = JSON.parse response.body
        expect(response.status).to eql 422
        expect(json_response['errors']['name'].first).to eql 'has already been taken'
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        { name: 'Contrato_H' }
      }

      it "updates the requested folder" do
        folder = Folder.create! valid_attributes
        patch folder_url(folder), params: { folder: new_attributes }
        folder.reload
        expect(folder.name).to eql(new_attributes[:name])
      end

      it "redirects to the folders index" do
        folder = Folder.create! valid_attributes
        patch folder_url(folder), params: { folder: new_attributes }
        folder.reload
        expect(response).to redirect_to(folders_url)
      end
    end

    context "with invalid parameters" do
      it "with request json return status 422 and message error" do
        folder = Folder.create! valid_attributes
        patch folder_url(folder), params: { folder: invalid_attributes }
        expect(response).to be_successful
      end
    end

    context "when invalid parameters and json request" do
      it "has 422 status code" do
        post folders_url, params: { folder: invalid_attributes }, as: :json
        json_response = JSON.parse response.body
        expect(response.status).to eql 422
        expect(json_response['errors']['name'].first).to eql 'has already been taken'
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested folder" do
      folder = Folder.create! valid_attributes
      expect {
        delete folder_url(folder)
      }.to change(Folder, :count).by(-1)
    end

    it "redirects to the folders list" do
      folder = Folder.create! valid_attributes
      delete folder_url(folder)
      expect(response).to redirect_to(folders_url)
    end
  end
end
